title: Moira Lampe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
# logo: <img src="/images/logo.png?raw=true" alt="Your Logo" style="border-radius: 50%; width; 100px; height 100px;">

description: > # your text below (remove <br> elements if you don't need line breaks)
  Computational Neuroscientist 
  <br>&amp; 
  <br>Machine Learning Engineer
  <br><br>
 
  

  <a href="www.linkedin.com/in/moira-lampe-303828282"></a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
